//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class alerta_pagos
    {
        public int ID { get; set; }
        public Nullable<int> ID_CUENTA_POR_PAGAR { get; set; }
        public Nullable<int> ID_CUENTA_POR_COBRAR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string ESTATUS { get; set; }
    }
}
