//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_cambios
    {
        public int ID { get; set; }
        public string MODULO { get; set; }
        public string TABLA { get; set; }
        public string ACCION { get; set; }
        public string ID_TABLA { get; set; }
        public string FECHA { get; set; }
        public string USUARIO { get; set; }
        public string UBSERVACIONES { get; set; }
    }
}
