//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacion()
        {
            this.cotizacion_producto = new HashSet<cotizacion_producto>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_VENDEDOR { get; set; }
        public Nullable<int> ID_TIENDA { get; set; }
        public System.DateTime FECHA_COTIZACION { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> VIGENCIA { get; set; }
        public Nullable<int> ID_CANAL_VENTA { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion_producto> cotizacion_producto { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual tienda tienda { get; set; }
    }
}
