//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas_por_cobrar
    {
        public int ID { get; set; }
        public decimal CANTIDAD { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public string TIPO { get; set; }
    }
}
