//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class etiquetas
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> NIVEL { get; set; }
        public Nullable<int> ID_LINEA_NEGOCIO { get; set; }
        public Nullable<int> ID_TIENDA { get; set; }
        public bool ACTIVO { get; set; }
    }
}
