//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class factor_canal_producto
    {
        public int ID_PRODUCTO { get; set; }
        public Nullable<double> FACTOR_POP { get; set; }
        public Nullable<double> FACTOR_CADENAS { get; set; }
        public Nullable<double> FACTOR_FRANQUICIA { get; set; }
        public Nullable<double> FACTOR_PROYECTOS { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
