//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class factor_fabrica_linea
    {
        public int ID_LINEA_NEGOCIO { get; set; }
        public double FACTOR_FABRICA { get; set; }
        public double DESCUENTO_POP { get; set; }
        public double DESCUENTO_CADENAS { get; set; }
        public double DESCUENTO_FRANQUICIA { get; set; }
        public double DESCUENTO_PROYECTOS { get; set; }
    
        public virtual linea_negocio linea_negocio { get; set; }
    }
}
