//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_precios
    {
        public int ID_PRODUCTO { get; set; }
        public decimal COSTO { get; set; }
        public decimal PRECIO_FABRICA { get; set; }
        public decimal PRECIO_POP { get; set; }
        public decimal PRECIO_CADENAS { get; set; }
        public decimal PRECIO_FRANQUICIA { get; set; }
        public decimal PRECIO_PROYECTOS { get; set; }
    }
}
