//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_precios_fabrica_v
    {
        public int ID_PRODUCTO { get; set; }
        public string PRODUCTO { get; set; }
        public string CODIGO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<double> FACTOR_FABRICA { get; set; }
        public Nullable<double> PRECIO_SUJERIDO_FABRICA { get; set; }
        public Nullable<decimal> PRECIO_FABRICA { get; set; }
        public Nullable<double> DESCUENTO_POP { get; set; }
        public Nullable<double> PRECIO_POP { get; set; }
        public Nullable<double> DESCUENTO_CADENAS { get; set; }
        public Nullable<double> PRECIO_CADENAS { get; set; }
        public Nullable<double> DESCUENTO_FRANQUICIA { get; set; }
        public Nullable<double> PRECIO_FRANQUICIA { get; set; }
        public Nullable<double> DESCUENTO_PROYECTOS { get; set; }
        public Nullable<double> PRECIO_PROYECTOS { get; set; }
        public string INDICADOR { get; set; }
    }
}
