//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia_prima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia_prima()
        {
            this.atributo_subatributo = new HashSet<atributo_subatributo>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> ID_ATRIBUTO { get; set; }
        public int PRESENTACION_COMPRA { get; set; }
        public int PRESENTACION_ENTREGA { get; set; }
        public string TIPO_COMPRA { get; set; }
        public string TIPO_EXPLOSION { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<decimal> PRECIO_ENTREGA { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual atributo_tipo atributo_tipo { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atributo_subatributo> atributo_subatributo { get; set; }
    }
}
