//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtexConnection : DbContext
    {
        public ArtexConnection()
            : base("name=ArtexConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alerta_pagos> alerta_pagos { get; set; }
        public virtual DbSet<almacen> almacen { get; set; }
        public virtual DbSet<archivo> archivo { get; set; }
        public virtual DbSet<archivos> archivos { get; set; }
        public virtual DbSet<area_almacen> area_almacen { get; set; }
        public virtual DbSet<area_trabajo> area_trabajo { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<atributo> atributo { get; set; }
        public virtual DbSet<atributo_subatributo> atributo_subatributo { get; set; }
        public virtual DbSet<atributo_tipo> atributo_tipo { get; set; }
        public virtual DbSet<bancos> bancos { get; set; }
        public virtual DbSet<bolo> bolo { get; set; }
        public virtual DbSet<bolo_composicion> bolo_composicion { get; set; }
        public virtual DbSet<bultos> bultos { get; set; }
        public virtual DbSet<canal_venta> canal_venta { get; set; }
        public virtual DbSet<catalogo_zonas> catalogo_zonas { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<color_mezcla> color_mezcla { get; set; }
        public virtual DbSet<color_mezcla_formulacion> color_mezcla_formulacion { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<concepto_producto> concepto_producto { get; set; }
        public virtual DbSet<configuracion_producto> configuracion_producto { get; set; }
        public virtual DbSet<configuracion_producto_cotizado> configuracion_producto_cotizado { get; set; }
        public virtual DbSet<configuracion_producto_piso> configuracion_producto_piso { get; set; }
        public virtual DbSet<configuracion_sistema> configuracion_sistema { get; set; }
        public virtual DbSet<control_cambios> control_cambios { get; set; }
        public virtual DbSet<corte_caja_diario> corte_caja_diario { get; set; }
        public virtual DbSet<costos_fabricacion> costos_fabricacion { get; set; }
        public virtual DbSet<cotizacion> cotizacion { get; set; }
        public virtual DbSet<cotizacion_producto> cotizacion_producto { get; set; }
        public virtual DbSet<criterio_de_evaluacion> criterio_de_evaluacion { get; set; }
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<cuentas_por_cobrar> cuentas_por_cobrar { get; set; }
        public virtual DbSet<cuentas_por_pagar> cuentas_por_pagar { get; set; }
        public virtual DbSet<descuentos> descuentos { get; set; }
        public virtual DbSet<devoluciones> devoluciones { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<disenio> disenio { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<estatus_pedido> estatus_pedido { get; set; }
        public virtual DbSet<estatus_servicio> estatus_servicio { get; set; }
        public virtual DbSet<estatus_sku> estatus_sku { get; set; }
        public virtual DbSet<estilo_producto> estilo_producto { get; set; }
        public virtual DbSet<etiquetas> etiquetas { get; set; }
        public virtual DbSet<exedentes> exedentes { get; set; }
        public virtual DbSet<factor_canal_familia> factor_canal_familia { get; set; }
        public virtual DbSet<factor_canal_linea> factor_canal_linea { get; set; }
        public virtual DbSet<factor_canal_producto> factor_canal_producto { get; set; }
        public virtual DbSet<factor_fabrica_familia> factor_fabrica_familia { get; set; }
        public virtual DbSet<factor_fabrica_linea> factor_fabrica_linea { get; set; }
        public virtual DbSet<factor_fabrica_producto> factor_fabrica_producto { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<familia_producto> familia_producto { get; set; }
        public virtual DbSet<forma_de_pago> forma_de_pago { get; set; }
        public virtual DbSet<formulacion> formulacion { get; set; }
        public virtual DbSet<formulacion_comodin> formulacion_comodin { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<insumo> insumo { get; set; }
        public virtual DbSet<linea> linea { get; set; }
        public virtual DbSet<linea_negocio> linea_negocio { get; set; }
        public virtual DbSet<linea_producto> linea_producto { get; set; }
        public virtual DbSet<lista_precios> lista_precios { get; set; }
        public virtual DbSet<maquinaria> maquinaria { get; set; }
        public virtual DbSet<materia_prima> materia_prima { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<ofertas> ofertas { get; set; }
        public virtual DbSet<orden_de_compra> orden_de_compra { get; set; }
        public virtual DbSet<pagos_realizados> pagos_realizados { get; set; }
        public virtual DbSet<pagos_recibidos> pagos_recibidos { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<permisos_especiales> permisos_especiales { get; set; }
        public virtual DbSet<permisos_modulo> permisos_modulo { get; set; }
        public virtual DbSet<persona_contacto> persona_contacto { get; set; }
        public virtual DbSet<persona_fisica> persona_fisica { get; set; }
        public virtual DbSet<persona_moral> persona_moral { get; set; }
        public virtual DbSet<piezas_configurables> piezas_configurables { get; set; }
        public virtual DbSet<piezas_producto> piezas_producto { get; set; }
        public virtual DbSet<presupuesto_anual_general> presupuesto_anual_general { get; set; }
        public virtual DbSet<presupuesto_anual_por_criterio> presupuesto_anual_por_criterio { get; set; }
        public virtual DbSet<presupuesto_por_empleado> presupuesto_por_empleado { get; set; }
        public virtual DbSet<presupuesto_semanal> presupuesto_semanal { get; set; }
        public virtual DbSet<proceso_fabricacion> proceso_fabricacion { get; set; }
        public virtual DbSet<proceso_maquina> proceso_maquina { get; set; }
        public virtual DbSet<procesos_de_fabricacion> procesos_de_fabricacion { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_orden_de_compra> producto_orden_de_compra { get; set; }
        public virtual DbSet<producto_proveedor> producto_proveedor { get; set; }
        public virtual DbSet<programa> programa { get; set; }
        public virtual DbSet<programacion_semanal> programacion_semanal { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<puntuacion> puntuacion { get; set; }
        public virtual DbSet<puntuacion__proceso> puntuacion__proceso { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<salida_de_mercancia> salida_de_mercancia { get; set; }
        public virtual DbSet<segmento> segmento { get; set; }
        public virtual DbSet<servicio_garantia> servicio_garantia { get; set; }
        public virtual DbSet<sett> sett { get; set; }
        public virtual DbSet<sett_producto> sett_producto { get; set; }
        public virtual DbSet<stock_intranet> stock_intranet { get; set; }
        public virtual DbSet<stock_tienda> stock_tienda { get; set; }
        public virtual DbSet<stok_insumo> stok_insumo { get; set; }
        public virtual DbSet<stok_producto> stok_producto { get; set; }
        public virtual DbSet<subprocesos_de_fabricacion> subprocesos_de_fabricacion { get; set; }
        public virtual DbSet<tienda> tienda { get; set; }
        public virtual DbSet<tipo_almacen> tipo_almacen { get; set; }
        public virtual DbSet<tipo_configuracion> tipo_configuracion { get; set; }
        public virtual DbSet<tipo_de_costo> tipo_de_costo { get; set; }
        public virtual DbSet<tipo_explosionado> tipo_explosionado { get; set; }
        public virtual DbSet<tipo_insumo> tipo_insumo { get; set; }
        public virtual DbSet<tipo_pedido> tipo_pedido { get; set; }
        public virtual DbSet<tipo_programa> tipo_programa { get; set; }
        public virtual DbSet<tipo_venta> tipo_venta { get; set; }
        public virtual DbSet<traspaso> traspaso { get; set; }
        public virtual DbSet<unidad_de_negocio> unidad_de_negocio { get; set; }
        public virtual DbSet<unidad_medida> unidad_medida { get; set; }
        public virtual DbSet<mapeo_costos> mapeo_costos { get; set; }
        public virtual DbSet<clientes_v> clientes_v { get; set; }
        public virtual DbSet<colores_v> colores_v { get; set; }
        public virtual DbSet<empleados_v> empleados_v { get; set; }
        public virtual DbSet<formulacion_comodin_v> formulacion_comodin_v { get; set; }
        public virtual DbSet<formulacion_v> formulacion_v { get; set; }
        public virtual DbSet<lista_precios_cadenas_v> lista_precios_cadenas_v { get; set; }
        public virtual DbSet<lista_precios_fabrica_v> lista_precios_fabrica_v { get; set; }
        public virtual DbSet<lista_precios_franquicias_v> lista_precios_franquicias_v { get; set; }
        public virtual DbSet<lista_precios_pop_v> lista_precios_pop_v { get; set; }
        public virtual DbSet<lista_precios_proyectos_v> lista_precios_proyectos_v { get; set; }
        public virtual DbSet<producto_v> producto_v { get; set; }
        public virtual DbSet<proveedores_v> proveedores_v { get; set; }
        public virtual DbSet<stock_intranet_v> stock_intranet_v { get; set; }
        public virtual DbSet<stock_tienda_v> stock_tienda_v { get; set; }
        public virtual DbSet<usuarios_v> usuarios_v { get; set; }
    }
}
