//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int ID { get; set; }
        public int ID_COTIZACION { get; set; }
        public int ANTICIPO { get; set; }
        public Nullable<int> FORMA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_PROPUESTA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public string TIPO_ENTREGA { get; set; }
        public Nullable<int> ID_ESTATUS_PEDIDO { get; set; }
        public Nullable<int> ID_PROGRAMACION_SEMANAL { get; set; }
        public Nullable<int> ID_TIPO_PEDIDO { get; set; }
        public Nullable<int> ID_TIPO_VENTA { get; set; }
        public Nullable<int> ID_CUENTA_POR_COBRAR { get; set; }
    }
}
