//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos_modulo
    {
        public int ID_MODULO { get; set; }
        public int ID_ROL { get; set; }
        public bool VER { get; set; }
        public bool CREAR { get; set; }
        public bool EDITAR { get; set; }
        public bool ELIMINAR { get; set; }
        public bool REPORTE { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual rol rol { get; set; }
    }
}
