//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto_semanal
    {
        public int ID { get; set; }
        public Nullable<int> SEMANA { get; set; }
        public Nullable<decimal> META { get; set; }
        public Nullable<decimal> CUMPLIMIENTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public int ID_PRESUPUESTO_ANUAL { get; set; }
    }
}
