//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.configuracion_producto = new HashSet<configuracion_producto>();
            this.configuracion_producto_piso = new HashSet<configuracion_producto_piso>();
            this.cotizacion_producto = new HashSet<cotizacion_producto>();
            this.descuentos = new HashSet<descuentos>();
            this.formulacion = new HashSet<formulacion>();
            this.formulacion_comodin = new HashSet<formulacion_comodin>();
            this.piezas_producto = new HashSet<piezas_producto>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_UNIDAD_NEGOCIO { get; set; }
        public int ID_LINEA_NEGOCIO { get; set; }
        public Nullable<int> ID_FAMILIA_PRODUCTO { get; set; }
        public int ID_STATUS_SKU { get; set; }
        public Nullable<int> ID_LINEA_PRODUCTO { get; set; }
        public Nullable<int> ID_CONCEPTO_PRODUCTO { get; set; }
        public Nullable<int> ID_SEGMENTO { get; set; }
        public Nullable<int> ID_ESTILO { get; set; }
        public bool ES_PERSONALIZABLE { get; set; }
        public Nullable<double> PUNTUACION { get; set; }
        public string FOTO { get; set; }
        public Nullable<int> ID_DISENIO { get; set; }
        public bool EDITABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<configuracion_producto> configuracion_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<configuracion_producto_piso> configuracion_producto_piso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion_producto> cotizacion_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<descuentos> descuentos { get; set; }
        public virtual factor_canal_producto factor_canal_producto { get; set; }
        public virtual factor_fabrica_producto factor_fabrica_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulacion> formulacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formulacion_comodin> formulacion_comodin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<piezas_producto> piezas_producto { get; set; }
    }
}
