//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_v
    {
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string FOTO { get; set; }
        public bool ES_PERSONALIZABLE { get; set; }
        public Nullable<double> PUNTUACION { get; set; }
        public int ID_LINEA_NEGOCIO { get; set; }
        public string LINEA_NEGOCIO { get; set; }
        public Nullable<int> ID_UNIDAD_NEGOCIO { get; set; }
        public int ID_STATUS_SKU { get; set; }
        public string STATUS_SKU { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> PRECIO_FABRICA { get; set; }
        public Nullable<decimal> PRECIO_POP { get; set; }
        public Nullable<decimal> PRECIO_CADENAS { get; set; }
        public Nullable<decimal> PRECIO_FRANQUICIA { get; set; }
        public Nullable<decimal> PRECIO_PROYECTOS { get; set; }
    }
}
