//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_orden_de_compra
    {
        public int ID { get; set; }
        public int ID_ORDEN_DE_COMPRA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<float> DESCUENTO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string CLAVE_CONFIRMACION { get; set; }
    }
}
