//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida_de_mercancia
    {
        public int ID { get; set; }
        public Nullable<int> ID_PEDIDO { get; set; }
        public Nullable<int> ID_QUIEN_AUTORIZA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public Nullable<int> ID_ALMACEN_ORIGEN { get; set; }
        public Nullable<int> ID_DIRECCION_DESTINO { get; set; }
        public Nullable<int> ID_ENCARGADO_DE_RUTA { get; set; }
        public Nullable<int> ID_GASTOS_DE_DISTRIBUCION { get; set; }
    }
}
