//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_intranet_v
    {
        public int ID { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public string PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CODIGO_PRODUCTO { get; set; }
        public string CODIGO_CONFIGURADO { get; set; }
        public int CANTIDAD { get; set; }
        public int DISPONIBLES { get; set; }
        public string NOTA { get; set; }
        public string FOTO { get; set; }
        public Nullable<bool> ES_PERSONALIZABLE { get; set; }
        public Nullable<double> PUNTUACION { get; set; }
        public Nullable<int> ID_TIENDA_ORIGEN { get; set; }
        public string TIENDA_ORIGEN { get; set; }
        public Nullable<int> ID_LINEA_NEGOCIO { get; set; }
        public string LINEA_NEGOCIO { get; set; }
        public Nullable<int> ID_UNIDAD_NEGOCIO { get; set; }
        public string UNIDAD_NEGOCIO { get; set; }
    }
}
