//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_intranet
    {
        public int ID { get; set; }
        public Nullable<int> ID_TIENDA_ORIGEN { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public string CODIGO { get; set; }
        public int CANTIDAD { get; set; }
        public int DISPONIBLES { get; set; }
        public string NOTA { get; set; }
    }
}
