//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_explosionado
    {
        public int ID { get; set; }
        public int ID_PROGRAMACION_SEMANAL { get; set; }
        public Nullable<int> ID_PEDIDO { get; set; }
        public Nullable<int> ID_INSUMO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    }
}
