//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artex.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_v
    {
        public string ID { get; set; }
        public int ID_ROL { get; set; }
        public string ROL { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public Nullable<int> ID_OTRA_PERSONA { get; set; }
        public string USUARIO { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public bool ACTIVO { get; set; }
    }
}
